$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: "Basic Pipeline Job with 3 Hello World components"

compute: azureml:Cluster-1-Small 

jobs:
  componentA_job:
    type: component
    component: file:./componentA.yml
  componentB_job:
    type: component
    component: file:./componentB.yml
  componentC_job:
    type: component
    component: file:./componentC.yml

